application: scrapitservices
version: 15-1-1-1
runtime: python27
api_version: 1

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images  

- url: /scripts
  static_dir: scripts

- url: /api.*
  script: api.py

- url: /
  script: index.py
  
- url: /scrapitservices/.*
  script: scrapitservices.py
  login: admin

- url: /businessservice/.*
  script: businessservice.py
  login: admin

- url: /status
  script: status.py
  login: admin