application: scrapitservices
version: 7
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts

- url: /api.*
  script: api.py

- url: /.*
  script: index.py