application: scrapitservices
version: 15-1-1-8
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images  

- url: /scripts
  static_dir: scripts

- url: /api.*
  script: api.app

- url: /
  script: index.app
  
- url: /about/.*
  script: about.app
  
- url: /scrapitservices/.*
  script: scrapitservices.app
  login: admin

- url: /businessservice/.*
  script: businessservice.app
  login: admin

- url: /status
  script: status.app
  login: admin