application: scrapitservices
version: 11
runtime: python
api_version: 1

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images  

- url: /scripts
  static_dir: scripts

- url: /api.*
  script: api.py

- url: /
  script: index.py
  
- url: /scrapitservices/.*
  script: scrapitservices.py
  login: admin